{% set name = "google-pasta" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-pasta-{{ version }}.tar.gz
  sha256: c9f2c8dfc8f96d0d5808299920721be30c9eec37f2389f28904f454565c8a16e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six

test:
  imports:
    - pasta
    - pasta.augment
    - pasta.base
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/pasta
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: pasta is an AST-based Python refactoring library

extra:
  recipe-maintainers:
    - jjhelmus
    - ocefpaf
