travis:
  secure:
    BINSTAR_TOKEN: EDSwSpq7PXJDx7CLYyB9DNj57RJCMO2w4te2dbsBdIyQSr3pgW91LldSGQVV6PCBo6R9kwDj5XmFxvAHOG8LpeetC3gMkjIbQdt6ORd0h1DC4+QcTtkkzwURnHdJITnME4X6DWHmm1xpWs9vKpoNqO1tKl27RN/YbPYPWUeP5uVwdVTg3qthXee4zwnmoTBM46fBwGfdg06yoeeWmVSf2ne+8dw8O+yurZ6CN3hrk83Jkgh8bSZlC8DJHoU37dtrpJ5nPrfdBLayHDvcwx5vInqMcNFj96+y6puqgcka2GgyQ3H/+U7bDcaF27C0T0puHCaAmOKZyEZZStkTSzYI0t3R3WqwKqjMyxBqIyE/dRWQoixVJo1LIbskCZRM9HiI3NOhsqpyWCLLAM6jPfl2aHp5swv5PJZXw8ygaIP7rI/bYCjuQ1b3tRLFcpQuZ4TAsNP/LFFT9V8nzsMsnoRBarZvFOrYVCyBv6yOk9uw0mgU9wXn1LCciahA9CwJW/QDnQ1N0HQGCic+ftk2v8LVipfFlHaYNHhz2MyNZwBW1M/PU33WqmBRVHYeoiBGV30bm8SbZgughAArtfxWHjsGHMVkkIdGeUh00zHiq0t2ZCFdPXPyjPsmlavrmHvrEa9EBsazIX18QUkV+Ie6uFT8l+4KdFL9J/1C0jxsJasI3WQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
